[package]
name = "mo-key-service-core"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
aes-gcm = { version = "0.10.3", features = ["aes"] }
argon2 = "0.5.3"
getrandom = "0.2.15"
hkdf = "0.12.4"
sha2 = "0.10.8"
zeroize = { version = "1.8.1", features = ["zeroize_derive"] }
thiserror = "1.0.63"
ed25519-dalek = { version = "2.1.1" }
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
ml-kem = { version = "0.3.0-pre.2", default-features = false, features = ["zeroize"] }
ml-dsa = { version = "0.1.0-rc.2", default-features = false, features = ["zeroize", "rand_core"] }
kem = "=0.4.0-pre.1"
rand_core = "0.9.3"
ciborium = "0.2.2"
hex = "0.4.3"
signature = "2.2.0"

[dev-dependencies]
